version: "3.9"
services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-81}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2.4.2}
    working_dir: /app/tamakiii-sandbox/init-symfony
    volumes:
      - ./dependency/tamakiii-sandbox/init-symfony:/app/tamakiii-sandbox/init-symfony:${MOUNT_TYPE:-delegated}
    ports:
      - 80:8000
