version: "3.9"
services:
  php:
    build:
      context: .
      args:
        VERSION: ${VERSION:-81}
    working_dir: /app/tamakiii-sandbox/init-symfony
    volumes:
      - ./dependency/tamakiii-sandbox/init-symfony:/app/tamakiii-sandbox/init-symfony:${MOUNT_TYPE:-delegated}
    ports:
      - 80:8000
